### ISSUE TITLE
Figure out how to properly manage Postgres strings

### ISSUE THREAD

**Issue by tskluzac** [xtracthub/xtracthub-service#4]
Right now in the crawler (see globus_base.py; lines 252-263) we do a lot of string manipulations to make our data fit the postgres schema. Find a library that does these so it doesn't look so 'gluesticks and paper'-y.

**Comment by tskluzac** [comment]
Doesn't seem there's a hard-and-fast 'library' solution to this.  
Created pg_list class that first checks for illegal Postgres characters in the string elements (e.g., --> ' ) and then switches the necessary sub-characters. 

It seems clean and concise, and the exceptions are handled, and trouble files are saved to a file (to be handled better later, among other trouble files).

**Comment by ryanchard** [comment]
Python's Postgres lib has a builtin for sanitizing inputs and protecting against injection attacks. I'm not sure if there is anything else you are doing in the pg_list class, but I'd suggest, if possible, you avoid rolling your own sanitizer as there are a lot of edge cases. I believe the built in even does dict -> json conversions. Anyway, the built in is included in the execute command -- you just have to pass all the parameters as a second input and let it do the string formatting rather than doing it yourself.

Here is an example: https://stackoverflow.com/questions/45128902/psycopg2-and-sql-injection-security

One little gotcha with the function is that the second parameter on execute needs to be a tuple. So if you are putting in just one value you need to make it a tuple, e.g., (name, ). Otherwise the execute command fails.

**Comment by tskluzac** [comment]
Closing as we've moved completely away from postgres into using queues. 

(but your contribution is not forgotten, Ryan!)
